name: CI - Build & Test NGINX App

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t nginx-static .

    - name: Run container
      run: docker run -d -p 8080:80 --name nginx-app nginx-static

    - name: Wait for container to start
      run: sleep 3

    - name: Smoke test
      run: curl -f http://localhost:8080

    - name: Stop container
      run: docker stop nginx-app
